### ISSUE TITLE
Xcode 8

### ISSUE THREAD

**Issue by smarison** [egold/better-xcode-ibeam-cursor#19]
The steps to fix the cursor don't seem to work with Xcode 8...

Any timeframe on an Xcode 8 solution?

Thanks!!!

**Comment by iOSerWzp** [comment]
same +1

**Comment by shaps80** [comment]
The DVTIbeamCursor no longer appears to exist.

**Comment by ebaker355** [comment]
Please see this thread: https://github.com/egold/better-xcode-ibeam-cursor/issues/16 Particularly, the comments from @cjheng regarding editing the Assets.car file using ThemeEngine.

When I tried to use ThemeEngine to edit the Assets.car file in Xcode 8, ThemeEngine crashed. Therefore, I have no way to create a binary patch to insert the modified cursor image.

Does anyone know how to edit that Assets.car file included with Xcode 8?

**Comment by shaps80** [comment]
I can open the current Xcode 8 `Assets.car` with ThemeEngine -- however it no longer appears to have the `DVTIbeamCursor` images from before. I also tried replacing the `Assets.car` with the Xcode 7.3.1 `Assets.car` with no luck

**Comment by allen-zeng** [comment]
ThemeEngine consistently crashes for me when opening `Assets.car` in Xcode 8. Did you figure out how to fix it?

**Comment by shaps80** [comment]
Seems to be working for me. I'll fork it tomorrow and send you the repo so you can try. I did have to fix the project but don't remember if it was something specific to a crash. More about getting Xcode issues out of the way. 

Shaps

**Comment by cjheng** [comment]
I find that ThemeEngine crashes when attempting to open `Assets.car` on El Capitan, but it manages to open it when running on Sierra.

However, as @shaps80 mentioned, it doesn't appear to contain `DVTIbeamCursor` images.

**Comment by allen-zeng** [comment]
Ooh interesting. 

I think the cursor is still in that file somewhere, it's just renamed to something else - because it does look slightly different from previous versions

**Comment by shaps80** [comment]
I am running Sierra too and it opens without issue as I mentioned. I didn't realise it was an issue with El Capitan. Interesting.

**Comment by shaps80** [comment]
The cursor in Xcode 8 is different but I couldn't see something that looked like it to me. Have you found it in the Assets.car file?

**Comment by cjheng** [comment]
Nothing caught my eye when I took a look at the files in Assets.car, but feel free to check again. I haven't spent much time looking since I'm still mainly using Xcode 7.3.1 and El Capitan at the moment.

**Comment by ebaker355** [comment]
I have searched thru all of the image files, and Assets.car files, included with Xcode 8, and I did not find the Ibeam cursor anywhere. (Its possible I missed it)

Additionally, I replaced Xcode8's Assets.car with the one from Xcode 7.3.1, then patched the file with the new Ibeam script. Xcode 8 still launched (surprisingly), but it did not use the updated Ibeam cursor. Wherever its pulling that cursor image from, its a totally new location than previous versions of Xcode.

I'm beginning to wonder if that cursor image has been removed from Xcode 8 completely.

**Comment by jwarrent** [comment]
I was also able to get ThemeEngine to compile in Xcode 8 on Sierra, but also couldn't locate the cursor graphic anywhere in or around the Assets.car file.  Hopefully some saint can figure out where they've hidden this thing!

In the mean time, I've resorted to enlarging the cursor in the Accessibility options, haha. <sigh>

**Comment by egold** [comment]
Sorry guys, it was a good ride while it lasted. Maybe in Xcode 9 they'll start letting us do stuff again. If anyone finds a workaround for Xcode 8, I'll buy you a beer. It seems like Xcode 8 is the hard-on-xcode-customizers release.

**Comment by JacobJT** [comment]
This is sad news. This was one of the few repos I used regularly :\ Why would they give 0 options for a dark theme friendly cursor?

**Comment by allen-zeng** [comment]
Well I think it's quite understandable, in a bad way. Because this seems to be the very least of Xcode's problems.

**Comment by trungnguyen1791** [comment]
Did you guys get any good news?

**Comment by alpriest** [comment]
I just used Mousecape to change my cursor and it seems to be working pretty well. Here's how I got it working on Xcode 8.1 and El Capitan 10.11.6.

1) Download Mousecape from https://github.com/alexzielenski/Mousecape/releases/tag/0.0.5 
2) Download the cursor from https://gist.github.com/alpriest/1fb8ab2c7406c7520b147a30f3f99c6b (this is the DVTIbeamCursor.tiff file built for Mousecape)
3) Run Mousecape and import the cursor
4) Apply the cursor

Unfortunately the modified cursor was lost after a reboot despite Mousecape being in my login items, but maybe it can be controlled from the command line.

**Comment by innocarpe** [comment]
@alpriest Thanks for your guidance! I finally changed my I-beam of Xcode in dark theme!
Could you tell me how I can handle preventing modified cursor from being lost via command line?

**Comment by alpriest** [comment]
@kwosu87 I've not tried using the command line yet - it was just a thought, there's some suggestions on the Mousecape site though that may help to maintain the cursor after a reboot https://github.com/alexzielenski/Mousecape/issues/64

**Comment by innocarpe** [comment]
@alpriest That's a good workaround! I applied that right away. Thanks!

**Comment by tallcoder** [comment]
Thanks for that ... that's working well. Pretty decent workaround.

**Comment by ebaker355** [comment]
@alpriest Fantastic! Thanks very much!

**Comment by cmako10** [comment]
I found what I believe to be the file at the path
Contents/OtherFrameworks/XcodeEdit.framework/Versions/A/Resources/TIbeam.tiff

**Comment by ebaker355** [comment]
@cmako10: great find! I will experiment with it when I can to see if applying the patch in this repo will work (or if someone else on this thread beats me to it, please share!)

In the meantime, I’ve been using the Mousecape workaround detailed in this thread, with good results.

**Comment by wuhh1991** [comment]
@alpriest Thanks very much! That's working well on Xcode 8.2.1

**Comment by Televisorino** [comment]
@alpriest thank you, worked fine in Xcode 8.2.1 and macOS Sierra (for now).

**Comment by netzfreak** [comment]
With Mousecape on Sierra 10.12.3 / Xcode 8.2.1 works perfect - Thank you for this top tip !

**Comment by nouatzi** [comment]
Hi, when I try to compile (Base SDK: macOS 10.12), I got this:
```
Undefined symbols for architecture x86_64:
  "_CGSIsCursorRegistered", referenced from:
      _MCIsCursorRegistered in MCDefs.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Build failed    31/05/2017, 17:33
```

**Comment by dinnerdeal** [comment]
I have given up on this and just manually changed the background color from black to a dark dark gray instead and its helped enough.

**Comment by GJNilsen** [comment]
I made a cursor for Mousecape, because the modified I-beam tiff file was not as I wanted it on retina screens. It has probably something to do with my eyesight, it has deteriorated lately. Anyhow, the one I made works great for me, so maybe someone else could use it as well.
[local.taf.taf.526242442.390419.cape.zip](https://github.com/egold/better-xcode-ibeam-cursor/files/1275466/local.taf.taf.526242442.390419.cape.zip)

Mousecape is acting up a bit when trying to export a zip, but I have added the cursor images as well if anyone wants it.

[ibeamImages.zip](https://github.com/egold/better-xcode-ibeam-cursor/files/1275470/ibeamImages.zip)
